### ISSUE TITLE
Memory leak when playing

### ISSUE THREAD

**Issue by blibourel** [FrontierPsychiatrist/node-spotify#102]
Hi, I use your module since few days and it works pretty well.
I have just one issue that i'm not able to fix, so I supposed it's a problem on your module or libspotify (I'm not able to determine what is going wrong)

I use node 0.10.23 with the 0.7.0 version of libspotify and I try to make a streamable url from the return of the usenodejsaudio callback.

I use express and I send the buffer returned by this callback to my express responses. At this time, the memory usage of my node application increase at the same speed of receiving buffer from the 'useNodejsAudio'. But when the playing is done, the memory seems not to be free. So I suppose it is a leak ?

If I can provide more information or test for you, let me know.
Thanks for this awesome plugin

**Comment by FrontierPsychiatrist** [comment]
So in general, V8 is garbage collected and it might very well be that the buffer objects just haven't been collected yet.

Can you try this out: https://simonmcmanus.wordpress.com/2013/01/03/forcing-garbage-collection-with-node-js-and-v8/ ?

Apart from that, I will probably release 0.7.5 soon (in 0.7.4 NodeJS audio is broken), maybe you can check again with that version.

If this still does not help some example code would be useful.

**Comment by blibourel** [comment]
I already tried to use the garbage collection call that isn't change the memory consumption.

Here a simple gist to show the issue:
https://gist.github.com/blibourel/be09ea9f9f5dc45fa070ff1abc6ae041

After playing the track (in fact I really do nothing with the buffer to be sure to not hold reference to it) the memory doesn't seems to be freed.

I tried to set up the max-stack-size of v8 option and other stuff, nothing seems to change the issue

**Comment by FrontierPsychiatrist** [comment]
Ok, thanks, I will try that out.

**Comment by FrontierPsychiatrist** [comment]
Can't recreate in NodeJS 6, the memory is being freed.

In NodeJS 0.10 it is indeed being held somewhere. The `free_data` in `NodeAudioHandler` is being called so I'm not sure where the problem is.

Can you upgrade to a newer NodeJS version?

**Comment by blibourel** [comment]
Thanks for you feedback. I will try it soon
