### ISSUE TITLE
Documentaion typo

### ISSUE THREAD

**Issue by Technoash** [FrontierPsychiatrist/node-spotify#105]
http://www.node-spotify.com/api/0.7.0/api.html#audio-handlers
`var resumeFunction = spotify.useNodjsAudio(handleAudio);`
should be 
`useNodejsAudio`

Caused me a lot of confusion when I copy/pasted. It looks correct too.

This is really useful. Thanks for making this! :)

**Comment by FrontierPsychiatrist** [comment]
Thanks for the heads up (and nice typo in the issue title ;). I will fix it.
