### ISSUE TITLE
node 6.9.1 compiling problems

### ISSUE THREAD

**Issue by afonsorp** [FrontierPsychiatrist/node-spotify#106]
when running _npm install node-spotify_ this warning shows a lot of times:

> warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/pi/.node-gyp/6.9.1/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
>      v8::Local<v8::Object> object = getConstructor()->NewInstance();

at the end, some files, like metadataUpdater.js and spotify.js, are not present

**Comment by FrontierPsychiatrist** [comment]
Hm, that seems just like a warning. The files should be copied though. What OS are you using?

**Comment by afonsorp** [comment]
That's what I thought, but the files are not there :/
right now I'm on armv6l GNU/Linux.

**Comment by afonsorp** [comment]
No news? this makes the node-spotify unusable. No possible workaround?
I can copy the js files from another version that successfully compiled. but that doesn't seem very right :/

**Comment by FrontierPsychiatrist** [comment]
Sorry, no, I was on vacation. I will try to have a look into it in the next two weeks.
