### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by pagrawl3** [FrontierPsychiatrist/node-spotify#36]
I there a way to set the volume for the song being played through spotify.player?

**Comment by himynameisjonas** [comment]
First: Thanks for an awesome lib. Currently rewriting a ruby app with node and this lib is really easy to use.

The only thing I miss from the ruby lib I used is the volume control. Any updates on this?

**Comment by floriancargoet** [comment]
You could try https://github.com/LinusU/node-loudness
It calls `amixer` on Linux and an AppleScript on OSX.

**Comment by FrontierPsychiatrist** [comment]
I could take a look on how to do this, but I don't know much about audio programming. In the meantime I suggest using third party libraries like @floriancargoet suggested.
