### ISSUE TITLE
Call ready callback with an error if login fails

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [FrontierPsychiatrist/node-spotify#62]
Currently the only thing that happens is that an error message is printed on the screen.

**Comment by milkisevil** [comment]
Would be great if you'd update the documentation to reflect the `err` being passed on http://www.node-spotify.com/api.html#spotify and especially the example on http://www.node-spotify.com/example.html

Thanks for the great work!

**Comment by FrontierPsychiatrist** [comment]
Yep, you're right, I'll update it. Thanks!

**Comment by FrontierPsychiatrist** [comment]
I've updated the example and made the documentation page (hopefully) more clear.
