### ISSUE TITLE
Follow Playlist Support

### ISSUE THREAD

**Issue by nzoschke** [FrontierPsychiatrist/node-spotify#68]
In the desktop UI, a user can follow any playlist object. I do not see how to do this with the node-spotify API, short of making a new playlist and adding all of another playlists tracks to it.

I believe in libspotify you do this by loading a playlist by a link and appending that Playlist object to the playlist container. But I am not sure.

**Comment by WeeJeWel** [comment]
+1, would love this functionality

**Comment by FrontierPsychiatrist** [comment]
Yep, it would be a cool feature. But unfortunately it's not in libspotify :(
