### ISSUE TITLE
playlistContainer Segmentation fault: 11

### ISSUE THREAD

**Issue by dannyobrian** [FrontierPsychiatrist/node-spotify#70]
Is there a limit on the number of playlists that node-spotify can handle?

The process crashes with Segementation fault: 11 whenever I try to interact with playlistContainer in any way.

I have this issue with both the precompiled node-spotify 0.6.0 for OSX and a natively compiled version 0.6.0 and 0.5.4 for Debian Wheezy.

I do have a large amount of playlists in my Spotify account but I wasn't having this issue a couple of  months ago using 0.5.3. but now even installing the older version results in a node process crash when interacting with playlistContainer

**Comment by OwenMelbz** [comment]
is there any movement on this as I'm also getting `segmentation fault: 11` when attempting to play a playlist

**Comment by FrontierPsychiatrist** [comment]
Currently no, sorry. Can you share the code that crashes for you, @OwenMelbz ?

**Comment by OwenMelbz** [comment]
@FrontierPsychiatrist not really sorry, I'm trying to setup https://github.com/crispymtn/crispyfi which seems to eventually use node-spotify, effectively its a API wrapper for it i believe, it all works fine until playing a playlist, then it returns the segmentation fault: 11 and crashes, theres no response from them so was hoping people over here had knowledge of what the error means

**Comment by FrontierPsychiatrist** [comment]
Hm, that includes older versions of node-spotify (0.6.0), would be nice to see if the problem persists when a newer one is used.

Which OS and node version do you run crispyfi on?

**Comment by RigMap** [comment]
Much appreciate your suggestion, I've just dropped in node-spotify 0.7.0 (no time to compile 0.7.1) run the script again and still returning segment fault 11.

Node: 0.10.2
NPM: 2.8.3
OS: Linux raspberrypi 3.18.7+ #755 PREEMPTarm6l GNU/Linux 7 Debian version 7.8 Raspbian GNU/Linux 7 (wheezy) Raspberry Pi Model B+

Thanks for your help, would love to get this solved!

**Comment by OwenMelbz** [comment]
Much appreciate your suggestion, I've just dropped in node-spotify 0.7.0 (no time to compile 0.7.1) run the script again and still returning segment fault 11.

Node: 0.10.2
NPM: 2.8.3
OS: Linux raspberrypi 3.18.7+ #755 PREEMPTarm6l GNU/Linux 7 Debian version 7.8 Raspbian GNU/Linux 7 (wheezy) Raspberry Pi Model B+

Thanks for your help, would love to get this solved!

**Comment by mtree** [comment]
```javascript
var spotify = require('./node_modules/node-spotify/build/Release/spotify')({ appkeyFile: 'spotify_appkey.key' });
var ready = function()  {
    var user = spotify.createFromLink('spotify:user:1196185159');
    var firstPublishedPlaylist = user.playlistContainer.getPlaylist(0);
    var track = firstPublishedPlaylist.getTrack(0);
    spotify.player.play(track);
};
spotify.on({
    ready: ready
});
spotify.login('', '', false, false);
```
this code also gives me "Segmentation fault: 11"
