### ISSUE TITLE
console.log(spotify) segfaults

### ISSUE THREAD

**Issue by floriancargoet** [FrontierPsychiatrist/node-spotify#79]
```
var spot = require('node-spotify')({appkeyFile:'spotify_appkey.key'});
console.log(spot); // segfault
```

node v0.10.35
node-spotify 0.7.0
linux kubuntu 14.04 64 bits

**Comment by FrontierPsychiatrist** [comment]
Yes, as the playlistcontainer is a property of the spotifiy object it's being rendered. But that calls libspotify functions without a session.

For 0.8 I'm thinking of returning a login/configure object and only providing the "real" spotify object after a successful login, in #23.

**Comment by floriancargoet** [comment]
I confirm that once logged in, it no longer crashes when printing the spotify object in the REPL.
