### ISSUE TITLE
spotify.createFromLink segmentation fault

### ISSUE THREAD

**Issue by drsounds** [FrontierPsychiatrist/node-spotify#80]
When calling createFromLink with an URI to a Spotify playlist, it crashes. I use it in a node webkit app.

spotify.createFromLink(uri);

**Comment by FrontierPsychiatrist** [comment]
Hi!
Have you logged in before using `createFromLink` and waited for the `ready` callback?
Best,
Moritz

**Comment by FrontierPsychiatrist** [comment]
Can't reproduce.

**Comment by sascha1337** [comment]
same error triggered here, some things are quite weird, big report coming soon..
