### ISSUE TITLE
spotify.player.pause() fail on raspberry pi

### ISSUE THREAD

**Issue by JeremyPouyet** [FrontierPsychiatrist/node-spotify#84]
I'm trying to implement node-spotify on a Linux raspberry pi (raspbian) 3.12.35+ #730 armv6l.

When I call spotify.player.pause(),  the music stop. But then, It's impossible to continue to play the current track or to play a new track.

The same code works perfectly on Ubuntu 14.04.

I use the Spotify player, not the NodeJs player.

**Comment by FrontierPsychiatrist** [comment]
I'll have to try that out - that is indeed strange behaviour.

**Comment by kashimsax** [comment]
This problem might be related to [my other problem](https://github.com/FrontierPsychiatrist/node-spotify/issues/86).

**Comment by kashimsax** [comment]
After an rpi_update, the pause is now working on raspbian.
