### ISSUE TITLE
Use node-pre-gyp for binary distribution.

### ISSUE THREAD

**Issue by bendi** [FrontierPsychiatrist/node-spotify#89]
Distributing pre-built binaries with npm is impossible but there exists module called [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) which (after small configuration) allows storing binaries in external location e.g. S3.

**Comment by FrontierPsychiatrist** [comment]
That's probably a good idea.

I guess the number of binaries is going to get quite large if I want to publish 0.10, 0.12 (is anyone using 0.11?) and io.js AND with/without native audio. I hope that's possible with node-pre-gyp.

**Comment by bendi** [comment]
Distinguishing between io.js/node was added recently, so it should be ok but I'm not sure about audio - this might be more tricky. I guess it might be adressed by custom patterns.

**Comment by FrontierPsychiatrist** [comment]
Do you know a good example that uses different node versions and architectures? To be honest I don't understand the documentation and what I am supposed to do.

When the publish command is executed do I need all compiled binaries I want to distribute? Or can I publish one version (like 0.8) for different archs (like x86_64, arm) and node versions one after another?

**Comment by bendi** [comment]
The documentation is indeed a bit confusing - when I was preparing configuration of my project I had to ask project owner some questions :)

A good example is (node-sqlite)[https://github.com/mapbox/node-sqlite3].

If you want to I can prepare a sample config for node-spotify on my issue-81 branch :)

**Comment by FrontierPsychiatrist** [comment]
Thanks, I'll take a look at node-sqlite. A kickstarter-sample config would be awesome!

**Comment by FrontierPsychiatrist** [comment]
As of 0.7.3 node-spotify uses node-pre-gyp. I pushed a NodeJS 6 build to S3 (for Linux).

Later I maybe will push builds for OSX and different NodeJS versions.

node-pre-gyp builds will always use ALSA/OpenAL, if you don't want that you have to build from source.
