### ISSUE TITLE
Bad documentantion?

### ISSUE THREAD

**Issue by brunocascio** [FrontierPsychiatrist/node-spotify#92]
`var spotify = require('node-spotify')(options);` instead of  `var spotify = require('spotify')(options);`

`ready callback` never execute

```
var options = {
    settingsFolder: 'settings',
    cacheFolder: 'cache',
    traceFile: 'trace.txt',
    appkeyFile: 'spotify_appkey.key'
}
var spotify = require('node-spotify')(options);


var ready = function() {
    console.log('node-spotify is ready to exeute more code!');
    //your apps functionality should start here
};

spotify.on({
    ready: ready
});
```

**Comment by FrontierPsychiatrist** [comment]
While you can require the native module directly I recommend using the thin Javascript wrapper (`require('spotify')` instead of `require('node-spotify')`). It adds some features and is consistent with the documentation.

The ready callback is executed after login.
