### ISSUE TITLE
INFO: Not building on io.js 1.X; fix pending

### ISSUE THREAD

**Issue by KenanSulayman** [FrontierPsychiatrist/node-spotify#93]
Hi,

just to inform people who are affected: the fix for the bad inlined **uv_tty_set_mode** is pending and awaits landing in io.js 1.6.2 (?) [-> https://github.com/libuv/libuv/pull/265/files]

Cheers

**Comment by zachfeldman** [comment]
@KenanSulayman so when will this be fixed? I now can't install on Mac OS X.

**Comment by KenanSulayman** [comment]
It landed in https://github.com/libuv/libuv/commit/252f3624c25415b875a194034503f9a124aa6bf6. What kind of issues are you dealing with?

**Comment by zachfeldman** [comment]
Here's the log with my issue (some paths edited for privacy)

`$ npm install node-spotify
/
> node-spotify@0.7.1 install ~/spot/node_modules/node-spotify
> node-gyp rebuild

  COPY Release/spotify.js
  COPY Release/metadataUpdater.js
  CXX(target) Release/obj.target/nodespotify/src/node-spotify.o
  CC(target) Release/obj.target/nodespotify/src/audio/audio.o
  CXX(target) Release/obj.target/nodespotify/src/audio/AudioHandler.o
  CXX(target) Release/obj.target/nodespotify/src/audio/NodeAudioHandler.o
In file included from ../src/audio/NodeAudioHandler.cc:1:
In file included from ../src/audio/NodeAudioHandler.h:4:
In file included from ../src/audio/AudioHandler.h:5:
In file included from ../src/audio/audio.h:30:
/Users/defaultuser/.node-gyp/0.12.2/deps/uv/include/uv.h:649:12: error: conflicting types for 'uv_tty_set_mode'
inline int uv_tty_set_mode(uv_tty_t* handle, int mode) {
           ^
/Users/defaultuser/.node-gyp/0.12.2/deps/uv/include/uv.h:642:15: note: previous declaration is here
UV_EXTERN int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode);
              ^
1 error generated.
make: *** [Release/obj.target/nodespotify/src/audio/NodeAudioHandler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/defaultuser/Dropbox/dev/alexa-spot/node_modules/node-spotify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-spotify"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-spotify@0.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-spotify@0.7.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-spotify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-spotify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    ~/spot/npm-debug.log`

**Comment by KenanSulayman** [comment]
```
/Users/defaultuser/.node-gyp/0.12.2/
```

This fix landed in io.js. I don't know when you can expect this fix in node-legacy.

**Comment by zachfeldman** [comment]
So how would I install node spotify in io.js instead of node.js? I'm frankly a bit new to the ecosystem.

**Comment by KenanSulayman** [comment]
If you fancy, you could use [ny](http://npmjs.com/package/ny), a version manager by me.

```
$ npm install -g ny
$ ny 1.8.1
```

Should install iojs 1.8.1.

```
$ ny 0.12.2
```

Should install node 0.12.2.

**Comment by felics** [comment]
fwiw, the build is failing for me in iojs 1.8.1.

```
> node-spotify@0.7.1 install /Users/eineente/Github/moodify/node_modules/node-spotify
> node-gyp rebuild

  COPY Release/spotify.js
  COPY Release/metadataUpdater.js
  CXX(target) Release/obj.target/nodespotify/src/node-spotify.o
  CC(target) Release/obj.target/nodespotify/src/audio/audio.o
  CXX(target) Release/obj.target/nodespotify/src/audio/AudioHandler.o
  CXX(target) Release/obj.target/nodespotify/src/audio/NodeAudioHandler.o
In file included from ../src/audio/NodeAudioHandler.cc:1:
In file included from ../src/audio/NodeAudioHandler.h:4:
In file included from ../src/audio/AudioHandler.h:5:
In file included from ../src/audio/audio.h:30:
/Users/eineente/.node-gyp/1.8.1/deps/uv/include/uv.h:649:12: error: conflicting
      types for 'uv_tty_set_mode'
inline int uv_tty_set_mode(uv_tty_t* handle, int mode) {
           ^
/Users/eineente/.node-gyp/1.8.1/deps/uv/include/uv.h:642:15: note: previous
      declaration is here
UV_EXTERN int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode);
              ^
1 error generated.
make: *** [Release/obj.target/nodespotify/src/audio/NodeAudioHandler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/eineente/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/eineente/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/eineente/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/eineente/Github/moodify/node_modules/node-spotify
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/eineente/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/eineente/.nvm/versions/io.js/v1.8.1/bin/npm" "install" "FrontierPsychiatrist/node-spotify" "--save"
npm ERR! node v1.8.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! node-spotify@0.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-spotify@0.7.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-spotify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-spotify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eineente/Github/moodify/npm-debug.log
```

**Comment by KenanSulayman** [comment]
Indeed, I tested with the relevant libuv. Looks like https://github.com/iojs/io.js/commit/b2a0d8f65e16e2299f8dab47cfe89233fee7931b didn't actually land all the changes included in 1.4.2, only a subportion of it. That is, you can manually fix it in the mean time by applying https://github.com/libuv/libuv/commit/252f3624c25415b875a194034503f9a124aa6bf6 yourself into /Users/eineente/.node-gyp/1.8.1/deps/uv/include/uv.h:649 ff.

**Comment by felics** [comment]
@KenanSulayman Works as of iojs 2.0.1 thanks for raising the issue with the devs, much appreciated!

**Comment by KenanSulayman** [comment]
Sure :beers:

**Comment by FrontierPsychiatrist** [comment]
I just tried to compile on my new linux box with node 0.12.2 and got the same error.

**Comment by KenanSulayman** [comment]
@FrontierPsychiatrist libuv 1.5.0 is far from landing in node 0.12; however, as outlined above, iojs 2.0.1 landed the fix.

**Comment by FrontierPsychiatrist** [comment]
That's just great, thanks for the heads up. I'll try io.js later.

**Comment by FrontierPsychiatrist** [comment]
Please recheck with 0.7.2 if this is still relevant.

**Comment by KenanSulayman** [comment]
Can confirm that it builds with Node 6, thanks.
