### ISSUE TITLE
Bitrate information

### ISSUE THREAD

**Issue by mtree** [FrontierPsychiatrist/node-spotify#95]
Is there any way to get bitrate of currently played song?

**Comment by FrontierPsychiatrist** [comment]
Hm, not in node-spotify. libspotify allows setting the preferred bitrate but I can't find a function to get the current bitrate that I could wrap.

**Comment by mtree** [comment]
@FrontierPsychiatrist: some time ago when i checked their app "Spotiamp" which is based on libspotify it allowed to see current song bitrate.
I remember that 50% of songs where at "middle quality" even though there was hq option turned on.

**Comment by FrontierPsychiatrist** [comment]
Interesting, I'll look it up. I have some free time in July and will hopefully be able to continue node-spotify a bit

**Comment by felixhammerl** [comment]
there seems to be this:

```
libspotify.sp_session_preferred_bitrate(sessionPtr, libspotify.sp_bitrate.BITRATE_320k);
```

see [here](https://developer.spotify.com/docs/libspotify/11.1.60/group__session.html#ga77ddd919314a7bb16140569af7a38fe2)
